site_name: Treinamento Processamento UCE UNESP 2025
site_description: Pipeline e fundamentos para processamento de dados UCE
site_author: Tiago Belintani

docs_dir: .

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

nav:
  - Início: README.md
  - Tutorial Completo: UCE_Phylogenomics_Tutorial.md
  - Ambiente:
      - GRID-UNESP: Acessando_GRID_UNESP.md
      - PuTTY e WinSCP: Utilizando_PuTTY_WinSCP.md
      - Comandos Shell: Comandos_Shell.md
      - Miniconda e PHYLUCE: Miniconda_and_PHYLUCE.md
      - Acessando e Editando Códigos: Acessando_Editando_codigos.md
  - Bibliografia: Bibliografia.md
